### ISSUE TITLE
All links in hello_world README are broken

### ISSUE THREAD

**Issue by jwillmer** [hashicorp/example-nomad-pack-registry#1]
Title concludes the problem.

**Comment by mikenomitch** [comment]
Thanks for the heads up - this pack was copied over from the community registry and it was using relative paths for the URLs.

Fixed and pushed!

**Comment by jwillmer** [comment]
The URL to the traefik pack is still broken in: https://github.com/hashicorp/example-nomad-pack-registry/blob/main/packs/hello_world/README.md
